# Docker images provided by https://github.com/cypress-io/cypress-docker-images
# this example mostly follows the GitLab example in
# https://github.com/cypress-io/cypress-example-kitchensink

# first, install Cypress, then run all tests (in parallel)
stages:
  - build
  - test

# to cache both npm modules and Cypress binary we use environment variables
# to point at the folders we can list as paths in "cache" job settings
variables:
  YARN_CACHE: "$CI_PROJECT_DIR/.yarn"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

# cache using branch name
# https://gitlab.com/help/ci/caching/index.md

# cache:
#   key: ${CI_COMMIT_REF_SLUG}
#   paths:
#     - .yarn
#     - node_modules

build:
  stage: build
  image: node:14-alpine
  script:
    # - yarn config set globalFolder ${YARN_CACHE}
    - yarn install
    - yarn nx run-many
      --target=build
      --all=true
      --configuration=production
      --verbose=true

test:
  image: node:14-alpine
  stage: test
  needs: [build]
  script:
    - yarn install
    - yarn nx run-many
      --target=test
      --all=true
      --verbose=true
      --coverage

lint:
  image: node:14-alpine
  stage: test
  needs: [build]
  script:
    - yarn install
    - yarn nx run-many
      --target=lint
      --all=true
      --verbose=true
