export { default as Github } from "./git-hub"
export { default as Dribble } from "./dribbble"
export { default as Facebook } from "./facebook"
export { default as Instagram } from "./instagram"
export { default as Twitter } from "./twitter"
export { default as Watheia } from "./watheia"
